In [2]:
import numpy as np
arr = np.array([1,2,3])

In [8]:
#dimensions and shape
a = np.array([[[]]])
a.ndim
a.shape

(1, 1, 0)

In [11]:
range = np.arange(1,11) # start stop step
print(range)

[ 1  2  3  4  5  6  7  8  9 10]


In [51]:
arr = np.linspace(0,3,5) # start stop number of values
print(arr)

[0.   0.75 1.5  2.25 3.  ]


In [50]:
arr = np.logspace(1,3,4) # logarithmic space array -> 10^1 -> 10^3
arr

array([  10.        ,   46.41588834,  215.443469  , 1000.        ])

In [14]:
arr = np.zeros(5) # zeros with size 5
arr

array([0., 0., 0., 0., 0.])

In [16]:
arr = np.zeros([2,3]) # 2 rows and 3 columns
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
arr = np.ones([4,2],dtype=str) # array full of 1
arr

array([['1', '1'],
       ['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [18]:
arr = np.full(10,2) # 10 elements with 2 value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
arr = np.full([2,4],7) # two rows 4 columns with 7 value
arr

array([[7, 7, 7, 7],
       [7, 7, 7, 7]])

In [20]:
arr = np.empty([2,3]) # create array with uninitialized values
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
arr = np.random.rand(10) #random floats(0 to 1) and no square brackets 
arr

array([0.24834412, 0.13965214, 0.25484183, 0.52239808, 0.47327051,
       0.62519966, 0.96206924, 0.93086701, 0.49047198, 0.64179844])

In [24]:
arr = np.random.randn(2,3) # randmon floats mean:0,standard deviation:1
arr

array([[ 0.8799815 , -0.08919538,  1.71657551],
       [-0.79633113,  0.09265929,  0.49903289]])

In [27]:
arr = np.random.randint(10,100,size=(2,3)) # randmon integer, start,stop,number of values
arr

array([[15, 82, 98],
       [31, 15, 84]])

<h1>Numpy Data Types and Type Casting</h1>

In [30]:
arr = np.array([1,2.1,3,4,5]) # all elements will be of float 
arr

array([1. , 2.1, 3. , 4. , 5. ])

In [31]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [33]:
arr = np.array([1,2,3,4],dtype=np.float32)
arr.dtype

dtype('float32')

In [34]:
#type casting -> astype()
arr = np.array([1,2,3])
arr.dtype

dtype('int32')

In [35]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

In [36]:
#Type Casting errors:
arr = np.array(['1','2','hello'])
arr2 = arr.astype(np.int64)

ValueError: invalid literal for int() with base 10: 'hello'

In [37]:
arr = np.array([[1,2,3],[4,5,6]]) # 2d array
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
arr.ndim

2

In [39]:
arr.shape # gives no. of rows and columns

(2, 3)

In [40]:
arr.size

6

In [42]:
arr.itemsize # in bytes

4

<h1>Array Reshaping -> Reshape,Ravel,Flatten</h1>

In [43]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3) # rows and columns
reshaped

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
#ravel -> convert 1D array
ravel = reshaped.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [46]:
#flatten -> to 1D array, returns a copy of array
flat = reshaped.flatten()
flat


array([1, 2, 3, 4, 5, 6])

<h1>Arithmetic Operations on Arrays</h1>


In [3]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)

[5 7 9]


In [4]:
print(a-b)

[-3 -3 -3]


In [5]:
print(a/b)

[0.25 0.4  0.5 ]


In [6]:
print(a*b)

[ 4 10 18]


In [8]:
print(b//a)

[4 2 2]


In [9]:
print(a%b)

[1 2 3]


In [11]:
print(a**2)

[1 4 9]


<h1>Universal Functions -> ufuncs</h1>

In [12]:
arr = np.array([1,4,9,16])
print(np.sqrt(arr))

[1. 2. 3. 4.]


In [14]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


In [15]:
angles = np.array([0,np.pi/2,np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


<h1>Indexing & Slicing</h1>

In [17]:
a = [1,2,3,4,5]
a[-1:-4:-1]

[5, 4, 3]

In [18]:
a[::2]

[1, 3, 5]

In [19]:
arr = np.array([10,20,30,40,50])
arr[::2]

array([10, 30, 50])

In [20]:
arr[-1]

50

In [21]:
matrix = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix[0:2,:]) # rows,columns

[[1 2 3]
 [4 5 6]]


In [22]:
print(matrix[1:,1:])

[[5 6]
 [8 9]]


In [24]:
arr = np.array([10,20,30,40,50])
ind=[0,2]
print(np.take(arr,ind)) # takes indices 

[10 30]


In [26]:
arr = np.array([[1,2],[3,4]])
for x in np.nditer(arr):
    print(x,end=" ")

1 2 3 4 

In [28]:
for ind,x in np.ndenumerate(arr): # index and value
    print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [29]:
arr = np.array([[1,2],[3,4]])
print(arr.transpose())

[[1 3]
 [2 4]]


In [30]:
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [31]:
swap = np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

In [32]:
print(arr)

[[[1 2]
  [3 4]]]


In [33]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6])

In [35]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [36]:
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [37]:
print(np.stack((arr1,arr2),axis=0)) # 0-> row 1-> column

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
arr1 = np.array([[1,2],[3,4],[5,6],[7,8]])
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [40]:
print(np.split(arr1,4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


In [41]:
print(np.hsplit(arr1,2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


In [42]:
#sum(),mean(),median(),std(),var(),min(),max()
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
print(np.sum(matrix,axis=1))

[ 6 15 24]


In [45]:
a

array([1, 2, 3])

In [46]:
print(np.cumsum(a)) # 1 1+2 1+2+3

[1 3 6]


In [48]:
print(np.cumprod(a)) # multiplication

[1 2 6]


<h1>Conditional Based Choices</h1>

In [50]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [51]:
result = np.where(arr<2,'low','high')
result

array(['low', 'high', 'high'], dtype='<U4')

In [52]:
arr = np.array([10,25,35,50])
print(np.argwhere(arr>0))

[[0]
 [1]
 [2]
 [3]]


In [53]:
mask = np.logical_and(arr>15,arr<35)
mask

array([False,  True, False, False])

In [54]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
print(np.argwhere(matrix>5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [56]:
arr

array([10, 25, 35, 50])

In [58]:
mask = np.logical_and(arr>3,arr<6)
mask

array([False, False, False, False])

In [59]:
arr[mask]

array([], dtype=int32)

In [60]:
mask = np.logical_or(arr>25,arr<50)
mask

array([ True,  True,  True,  True])

<h1>Broadcasting</h1>

In [2]:
import numpy as np
image = np.array([[200,150],[150,250]])
brightness = image + 50
brightness

array([[250, 200],
       [200, 300]])

In [3]:
image.shape

(2, 2)

<h1>Vectorization</h1>

In [6]:
def square(x):
    return x*x
vfunc = np.vectorize(square)
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [7]:
print(vfunc(arr))

[ 1  4  9 16 25 36]


<h1>Dealing with missing values</h1>

In [9]:
a = np.array([1,2,np.inf,4])
a

array([ 1.,  2., inf,  4.])

In [ ]:
#np.isnan
#np.isinf
#np.isinfinite